package com.asaddour.autoroomdao.models

import android.arch.persistence.room.ColumnInfo
import android.arch.persistence.room.Entity
import android.arch.persistence.room.Ignore
import android.arch.persistence.room.PrimaryKey

@Entity(tableName = "users")
data class User(
        @PrimaryKey(autoGenerate = true)
        var id: Long = 0,
        var name: String = "",
        var age: Int = 0,

        // AutoRoomDao will care about "ColumnInfo.name"
        @ColumnInfo(name = "remote_id") var remoteId: Int = 0,

        // Nothing will be generated by AutoRoomDao for "job"
        @Ignore var job: String = ""
)