package com.asaddour.autoroomdao.models

import androidx.room.*

@Entity(tableName = "users")
data class User(
        @PrimaryKey(autoGenerate = true)
        var id: Long = 0,
        var name: String = "",
        var age: Int = 0,
        // AutoRoomDao supports `Embedded`
        @Embedded(prefix = "address_") var address: Address? = null,
        // AutoRoomDao will care about `ColumnInfo.name`
        @ColumnInfo(name = "remote_id") var remoteId: Int = 0,
        // Nothing will be generated by AutoRoomDao for `job`
        @Ignore var job: String = ""
) {
    data class Address(
            var street: String,
            // AutoRoomDao supports `ColumnInfo` inside `Embedded`
            @ColumnInfo(name = "city_home")
            var city: String
    )
}

